export const DummyData = [
    {
        key: "1",
        firstname: "John",
        lastname: "Brown",
        birthdate: "22/09/1993",
        joindate: "02/06/2019",
        role: "Developer",
        department: "R&D",
        shirtsize: "L",
        food: "regular",
        phone: "0525910000",
        married: "false",
        tags: ["1", "2"],
        student: "true",
        graduation: "",
        email: "ddd@gmail.com",
        address: "Kaplan 1, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "2",
        firstname: "Almog",
        lastname: "Brown",
        birthdate: "12/08/1992",
        joindate: "02/07/2022",
        role: "Developer",
        department: "R&D",
        shirtsize: "M",
        food: "kosher",
        phone: "0525810000",
        married: "Yes",
        tags: [],
        student: "true",
        graduation: "",
        email: "AAA@gmail.com",
        address: "Mashehu, Netanya",
        isAdmin: "false",
    },
    {
        key: "3",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "XS",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "4",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "XS",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "5",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "XXXS",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "6",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "XS",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "7",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "8",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "kosher",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "9",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "10",
        firstname: "Elad",
        lastname: "Brown",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },

]