export const DummyData = [
    {
        key: "1",
        name: "John Brown",
        birthdate: "22/09/1993",
        joindate: "02/06/2019",
        role: "Developer",
        department: "R&D",
        shirtsize: "L",
        food: "regular",
        phone: "0525910000",
        married: "false",
        tags: ["1", "2"],
        student: "true",
        graduation: "",
        email: "ddd@gmail.com",
        address: "Kaplan 1, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "2",
        name: "Almog Levi",
        birthdate: "12/08/1992",
        joindate: "02/07/2022",
        role: "Developer",
        department: "R&D",
        shirtsize: "M",
        food: "kosher",
        phone: "0525810000",
        married: "Yes",
        tags: [],
        student: "true",
        graduation: "",
        email: "AAA@gmail.com",
        address: "Mashehu, Netanya",
        isAdmin: "false",
    },
    {
        key: "3",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "4",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "5",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegeterian",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "6",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "7",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "8",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "kosher",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "9",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
    {
        key: "10",
        name: "Elad Kaufman",
        birthdate: "12/08/1991",
        joindate: "02/06/2018",
        role: "Developer",
        department: "Automation",
        shirtsize: "S",
        food: "vegan",
        phone: "0525810021",
        married: "NO",
        tags: [],
        student: "false",
        graduation: "22/05/2023",
        email: "CCC@gmail.com",
        address: "Mashehu2, Tel Aviv",
        isAdmin: "false",
    },
]